### ISSUE TITLE
Eyes excessively spawning help!

### ISSUE THREAD

**Issue by MagnataRPL** [gigaherz/EyesInTheDarkness#13]
In a clear install with the **Forge 35.1.29** the eyes are spawning everywhere, even if you fly away in creative on the night you can see they spawning on every place you look. **I tried changing overrideWeight** to 5, then 2, and then 1 in **config/eyesinthedarkness-common** and it didnt make any changes. It still keeps spawning somewhere between 15 eyes instantly every place I go. Does note that i'm running a clear install with only this mod installed on **1.16.4 Forge version 35.1.29**

I love this mod, thanks for the attention!

**Comment by gigaherz** [comment]
Uhm, are you in peaceful mode or something? They shouldn't spawn THAT fast, I don't think? I'll look into it...

**Comment by MagnataRPL** [comment]
Nope, im on Normal mode on a fresh new world

**Comment by Camawama** [comment]
yeah, the eyes spawn everywhere in every dimension.

You should also add a way to turn down the mod. I wanted to have it be a part of my modpack but people are complaining that it's "too loud" and that I should "uninstall it". I think they're just mad it scared them, lol. Seriously though, A sound setting would be nice!

**Comment by gigaherz** [comment]
Now that's a feature request I can easily do and would help everyone. A volume setting! Didn't even occur to me. :D

As for spawning excessively, I have started working on a custom spawning system, that will ignore the vanilla spawning process. This will mean mods that tweak/control entity spawns may not work anymore (I'll try to keep sending the same notifications so they can, but I can't promise anything), but in exchange, the spawn rate and entity limits will be configurable, just like I already have biome rules.

**Comment by Camawama** [comment]
Very excited to hear about that being worked upon! Thank you for your time and dedication to this Mod and thank you for actually listening to feedback. I know a lot of other Mod Devs that don't, it's nice to be able to bring up a problem and have it addressed in a timely manner :smile:

**Comment by gigaherz** [comment]
I just released v1.0.0, which includes a custom spawning system, which doesn't suffer of runaway spawning, among other things!
And yes, volumes are one of those other things!
