### ISSUE TITLE
Skipping entity with id

### ISSUE THREAD

**Issue by terrapin47** [gigaherz/EyesInTheDarkness#2]
After removing the mod, I get the message `Skipping Entity with id eyesinthedarkness:eyes` in my server log.

From what I understand this appears to be an error with how the entity was registered/unregistered.

**Comment by gigaherz** [comment]
Asked around, seems this is normal behaviour when you remove a mod that adds entities, nothing I can fix because it's not a bug in my code. If you know anything more, I'll be happy to reopen.
