### ISSUE TITLE
Eyes spawning in nether

### ISSUE THREAD

**Issue by GauntAndreX8** [gigaherz/EyesInTheDarkness#21]
They are spawning in the nether is this bug or something

**Comment by gigaherz** [comment]
no it's not a bug. you can configure it.

**Comment by GauntAndreX8** [comment]
Where can I configure it

**Comment by gigaherz** [comment]
depends on what version of mc you use and what version of the mod.

assuming a recent version, in the save folder,
```
saves/<save folder>/serverconfigs/eyesinthedarkness-server.toml
```
or in a server
```
world/serverconfigs/eyesinthedarkness-server.toml
```

if you are in a new enough version there will be a dimension blacklist option.

**Comment by GauntAndreX8** [comment]
Where is it tho go to minecraft then config then eyes in the darkness that’s the only config this mod has

**Comment by GauntAndreX8** [comment]
How do I config not spawn in the nether I am playing in Minecraft 1.16.5 on mod version 1.0.3

**Comment by gigaherz** [comment]
it explains in the comment lines before "DimensionRules": 
```
	#Specifies rules for accepting or rejecting dimensions.
	#The rules are scanned one by one until a rule matches, This means the first rule to match takes precedence over any other subsequent rule, so more specific rules should go first.
	#Rules:
	#  "dimension:name"   -- ALLOWS spawning in the given dimension.
	#  "!dimension:name"  -- DISALLOWS spawning in the given dimension.
	#  "#dimension:type"  -- ALLOWS spawning in any dimension with the given dimension type.
	#  "!#dimension:type" -- DISALLOWS spawning in any dimension with the given dimension type.
	#  "!*"               -- DISALLOWS spawning unconditionally. Place this at the end of the list to disable spawning if no other rules pass (defaults to allow otherwise).
	#Examples:
	#  To disable spawning in the end dimension: [ "!minecraft:the_end" ]
	#  To disable spawning in the nether dimension: [ "!minecraft:nether" ]
	#  To disable spawning in all secondary overworlds, but allow the vanilla overworld: [ "minecraft:overworld", "!#minecraft:overworld" ]
```

if you just want to disable in the nether, you can use what the comment says, and just make the line:
```
	DimensionRules = [ "!minecraft:the_nether" ]
```

**Comment by GauntAndreX8** [comment]
But there’s only a client side config how many config does this mod have

**Comment by gigaherz** [comment]
As I said in the other message, it's in the **serverconfig** folder, in your save, not the main config folder.

Try using https://www.curseforge.com/minecraft/mc-mods/configured
Maybe it will be easier for you.

**Comment by GauntAndreX8** [comment]
I do have it when I went to config it only shows if jumpscare should be on or off I even did it manually by the folder and still none

**Comment by gigaherz** [comment]
It has to be there, in the serverconfig folder. This has been working for years, so I don't know why it wouldn't be there. Are you sure you looked in the right folder? `<save>/serverconfigs/eyesinthedarkness-server.toml` ?

**Comment by GauntAndreX8** [comment]
I’ll have a look and see

**Comment by GauntAndreX8** [comment]
![image](https://user-images.githubusercontent.com/85809443/133897449-bd4359f4-9142-451a-8eb2-dcf7cd7fd486.jpg)
![image](https://user-images.githubusercontent.com/85809443/133897454-c594e160-aedf-421d-9e28-8d95c43f3b20.jpg)
![image](https://user-images.githubusercontent.com/85809443/133897467-c5a2a5bb-e523-407c-9ca3-5afd804810d2.jpg)

**Comment by GauntAndreX8** [comment]
That’s the config I see with configured mod

**Comment by gigaherz** [comment]
Try looking for it in explorer instead of using Configured, then.

**Comment by GauntAndreX8** [comment]
![image](https://user-images.githubusercontent.com/85809443/133897509-d74a086a-2dbf-4572-b92b-dd3018db7101.jpg)
![image](https://user-images.githubusercontent.com/85809443/133897518-737a2f26-7b17-4a2b-8a63-972ef99a1319.jpg)
![image](https://user-images.githubusercontent.com/85809443/133897528-e03d3008-3576-4dd2-90a5-9df1c9650ec4.jpg)

**Comment by GauntAndreX8** [comment]
The same too

**Comment by gigaherz** [comment]
That's the wrong file!
It's **not** eyesinthedarkness-client.toml in the config folder.
You have to go to your **save folder**, and then into the **serverconfigs** folder, and then look for eyesinthedarkness-server.toml there.
![image](https://user-images.githubusercontent.com/685851/133897577-85424f21-d4c1-42dd-a70c-79782fea686d.png)
![image](https://user-images.githubusercontent.com/685851/133897593-d23b39c2-4931-47d4-8357-1c8db583b8e1.png)
![image](https://user-images.githubusercontent.com/685851/133897581-d91ab2a0-5d4c-4315-9b72-3459c64b09a9.png)
![image](https://user-images.githubusercontent.com/685851/133897587-80b3f0f1-8b6a-424b-ba29-85ee6269d9cb.png)

**Comment by GauntAndreX8** [comment]
But there is nothing in my saves I have no official worlds I keep yet also will apply generally or only in the world I config

**Comment by gigaherz** [comment]
Once you have configured your configs to your liking, you can copy the serverconfigs contents to the defaultconfigs folder outside.
![image](https://user-images.githubusercontent.com/685851/133897685-ece54113-299a-4acb-ba49-25f5504d5904.png)
![image](https://user-images.githubusercontent.com/685851/133897690-30f50e82-5969-492d-8648-deb160dc0acc.png)
the files there will be copied to all new saves but forge will never replace existing files in existing saves.

**Comment by GauntAndreX8** [comment]
So it will change the config generally like if I create a new world it will still use the config I change or will still use the original

**Comment by gigaherz** [comment]
Once you have copied a config file to the defaultconfigs, forge will apply that config to all **new** saves.
If you modify the file on a save the configs will only apply to that one save.

**Comment by GauntAndreX8** [comment]
Ok thxs I’ll see and try if it helps
