### ISSUE TITLE
[1.21.1] [Neoforge] Crash when looking at eyes

### ISSUE THREAD

**Issue by BugmanBugman** [gigaherz/EyesInTheDarkness#30]
https://gist.github.com/BugmanBugman/a9246062f36e1483e9d1019f6d4b2782

**Comment by gigaherz** [comment]
I'm very confused by this crash but I will take a look this afternoon.

**Comment by Daltaxy** [comment]
> I'm very confused by this crash but I will take a look this afternoon.

same issue today
[crash-2024-09-18_00.45.31-server.txt](https://github.com/user-attachments/files/17036158/crash-2024-09-18_00.45.31-server.txt)
or
https://mclo.gs/UlJfW2g

also latest.log:
https://mclo.gs/GKaudvc

**Comment by Lolothepro** [comment]
I can confirm this bug

**Comment by gigaherz** [comment]
OMG I completely forgot about this. 🤦‍♂️
I have loaded the project in latest neoforge 1.21.1 and I can confirm it happens in dev too.
I will report back once I figure out *why* it happens.

**Comment by gigaherz** [comment]
![image](https://github.com/user-attachments/assets/ac894b54-0457-4328-bee8-69801a1807b1)

Boo!

Err, I mean, a bugfix is already out on CF for 1.21.1, and the 1.21.3 port is in review.
