### ISSUE TITLE
Minor config error

### ISSUE THREAD

**Issue by DWX12** [gigaherz/EyesInTheDarkness#5]
Came across this in the config, which I'm sure is just an error:

    # Set to false to disable the jumpscare system.
    # Min: 0
    # Max: 6
    B:Jumpscare=true

The jumpscare is either true or false, correct? Or is there some varying degree to it?

Thanks for creating such a cool mod.

**Comment by gigaherz** [comment]
Yeah it's fixed locally. Found it literally right after submitting the build for review. Switched back to Intellij to switch to another project, and I see that glaring `@Config.RangeInt(0,6)` right there staring at me...

**Comment by gigaherz** [comment]
Fixed as of the just-released 0.1.0 (gee talk about neglecting this mod...)
