### ISSUE TITLE
Crashing my game

### ISSUE THREAD

**Issue by slard3** [gigaherz/EyesInTheDarkness#7]
This mod crashes the game sometimes when  I try to load a world, sometimes when I try to save and quit to the game menu.

Crash report: https://hastebin.com/adopicecek.rb

**Comment by gigaherz** [comment]
Hm.... that's annoying. I'll fix asap.

**Comment by Nukeologist** [comment]
Hey - sorry about that. Didn't realize that could happen in my port. I saw that the EntitySpawnPlacementRegistry registry field is private. There's three ways that I can think of to fix this, one by registering the spawn placement only once in a Forge lifecycle event, even if the config is set to no natural spawning. The other way is by using reflection/access transformer to check if it was registered already. The last way I am not sure if it was intended, but the entity still seems to spawn if you don't register a spawn placement at all (in my testing). Either way, if you are busy, I can help if you want.

**Comment by gigaherz** [comment]
Don't worry it's fixed locally already. I just want to finish a new feature I had half-done.

**Comment by gigaherz** [comment]
v0.2 should fix the issue. It also comes with a new feature that can be turned off if needed. :P

**Comment by slard3** [comment]
Thanks for the fix :) I guess I'll close this
